# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscore.proto\x12\x05score\"&\n\x12StreamScoreRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\"\xe7\x02\n\x13StreamScoreResponse\x12\r\n\x05score\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61tsman\x18\x02 \x01(\t\x12\x16\n\x0e\x63urrentrunrate\x18\x03 \x01(\t\x12\x13\n\x0b\x62\x61ttingteam\x18\x04 \x01(\t\x12\x13\n\x0b\x62owlingteam\x18\x05 \x01(\t\x12\x0f\n\x07innings\x18\x06 \x01(\t\x12\x0f\n\x07wickets\x18\x07 \x01(\t\x12\r\n\x05overs\x18\x08 \x01(\t\x12\x12\n\ntosswinner\x18\t \x01(\t\x12\x14\n\x0ctossdecision\x18\n \x01(\t\x12\r\n\x05team1\x18\x0b \x01(\t\x12\r\n\x05team2\x18\x0c \x01(\t\x12\x0f\n\x07umpire1\x18\r \x01(\t\x12\x0f\n\x07umpire2\x18\x0e \x01(\t\x12\x0f\n\x07umpire3\x18\x0f \x01(\t\x12\r\n\x05venue\x18\x10 \x01(\t\x12\x0f\n\x07matchid\x18\x11 \x01(\t\x12\x12\n\nnonStriker\x18\x12 \x01(\t\x12\x0e\n\x06\x62owler\x18\x13 \x01(\t2W\n\x0bScoreStream\x12H\n\x0bStreamScore\x12\x19.score.StreamScoreRequest\x1a\x1a.score.StreamScoreResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'score_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMSCOREREQUEST._serialized_start=22
  _STREAMSCOREREQUEST._serialized_end=60
  _STREAMSCORERESPONSE._serialized_start=63
  _STREAMSCORERESPONSE._serialized_end=422
  _SCORESTREAM._serialized_start=424
  _SCORESTREAM._serialized_end=511
# @@protoc_insertion_point(module_scope)
